"""add phone_number to USERS table

Revision ID: 96beb92bf4d3
Revises: 0d5310fe5b14
Create Date: 2022-11-20 17:24:49.596993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96beb92bf4d3'
down_revision = '0d5310fe5b14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
